### ISSUE TITLE
error while launching setup.py (stratum-mining)

### ISSUE THREAD

**Issue by matteocs95** [MPOS/php-mpos#2572]
please help me to fix this issues: when I launch setup.py in stratum-mining/externals/stratum i get this error

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Extracting in /tmp/tmpAgPY4C
Now working in /tmp/tmpAgPY4C/distribute-0.6.28
Building a Distribute egg in /home/pooluser/stratum-mining/externals/stratum
Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    exec(open(init_path).read(), d)
  File "<string>", line 8, in <module>
  File "/tmp/tmpAgPY4C/distribute-0.6.28/setuptools/__init__.py", line 2, in <module>
    from setuptools.extension import Extension, Library
  File "/tmp/tmpAgPY4C/distribute-0.6.28/setuptools/extension.py", line 5, in <module>
    from setuptools.dist import _get_unpatched
  File "/tmp/tmpAgPY4C/distribute-0.6.28/setuptools/dist.py", line 6, in <module>
    from setuptools.command.install import install
  File "/tmp/tmpAgPY4C/distribute-0.6.28/setuptools/command/__init__.py", line 8, in <module>
    from setuptools.command import install_scripts
  File "/tmp/tmpAgPY4C/distribute-0.6.28/setuptools/command/install_scripts.py", line 3, in <module>
    from pkg_resources import Distribution, PathMetadata, ensure_directory
  File "/tmp/tmpAgPY4C/distribute-0.6.28/pkg_resources.py", line 2835, in <module>
    add_activation_listener(lambda dist: dist.activate())
  File "/tmp/tmpAgPY4C/distribute-0.6.28/pkg_resources.py", line 704, in subscribe
    callback(dist)
  File "/tmp/tmpAgPY4C/distribute-0.6.28/pkg_resources.py", line 2835, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/tmp/tmpAgPY4C/distribute-0.6.28/pkg_resources.py", line 2259, in activate
    self.insert_on(path)
  File "/tmp/tmpAgPY4C/distribute-0.6.28/pkg_resources.py", line 2360, in insert_on
    "with distribute. Found one at %s" % str(self.location))
ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/lib/python2.7/dist-packages
/home/pooluser/stratum-mining/externals/stratum/distribute-0.6.28-py2.7.egg
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/home/pooluser/stratum-mining/externals/stratum/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pooluser/stratum-mining/externals/stratum/distribute_setup.py", line 125, in _do_download
    _build_egg(egg, tarball, to_dir)
  File "/home/pooluser/stratum-mining/externals/stratum/distribute_setup.py", line 116, in _build_egg
    raise IOError('Could not build the egg.')
IOError: Could not build the egg.

**Comment by TheSerapher** [comment]
This is the MPOS bug tracker, not the support forum for the stratum of your choice.
