### ISSUE TITLE
Error when setting up - using Quick Start Guide

### ISSUE THREAD

**Issue by Flare183** [MPOS/php-mpos#2600]
Python is throwing me an error when I try to compile stratum from the external's folder:

jesse@onyx:~/Mining-Pool/stratum-mining/externals/stratum$ sudo python setup.py install
running install
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to stratum.egg-info/requires.txt
writing stratum.egg-info/PKG-INFO
writing top-level names to stratum.egg-info/top_level.txt
writing dependency_links to stratum.egg-info/dependency_links.txt
writing requirements to stratum.egg-info/requires.txt
writing stratum.egg-info/PKG-INFO
writing top-level names to stratum.egg-info/top_level.txt
writing dependency_links to stratum.egg-info/dependency_links.txt
reading manifest file 'stratum.egg-info/SOURCES.txt'
writing manifest file 'stratum.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-2.7/distribute_setup.py -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/__init__.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/config_default.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/connection_registry.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/custom_exceptions.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/event_handler.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/example_service.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/helpers.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/http_transport.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/irc.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/jsonical.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/logger.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/protocol.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/pubsub.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/semaphore.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/server.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/services.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/settings.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/signature.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/socket_transport.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/socksclient.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/stats.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/storage.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/version.py -> build/bdist.linux-x86_64/egg/stratum
copying build/lib.linux-x86_64-2.7/stratum/websocket_transport.py -> build/bdist.linux-x86_64/egg/stratum
byte-compiling build/bdist.linux-x86_64/egg/distribute_setup.py to distribute_setup.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/config_default.py to config_default.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/connection_registry.py to connection_registry.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/custom_exceptions.py to custom_exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/event_handler.py to event_handler.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/example_service.py to example_service.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/helpers.py to helpers.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/http_transport.py to http_transport.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/irc.py to irc.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/jsonical.py to jsonical.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/logger.py to logger.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/protocol.py to protocol.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/pubsub.py to pubsub.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/semaphore.py to semaphore.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/server.py to server.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/services.py to services.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/settings.py to settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/signature.py to signature.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/socket_transport.py to socket_transport.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/socksclient.py to socksclient.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/stats.py to stats.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/storage.py to storage.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/version.py to version.pyc
byte-compiling build/bdist.linux-x86_64/egg/stratum/websocket_transport.py to websocket_transport.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying stratum.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/stratum-0.2.13-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing stratum-0.2.13-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg
Extracting stratum-0.2.13-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding stratum 0.2.13 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/stratum-0.2.13-py2.7.egg
Processing dependencies for stratum==0.2.13
Searching for autobahn
Reading http://pypi.python.org/simple/autobahn/
Best match: autobahn 17.9.3
Downloading https://pypi.python.org/packages/68/ed/a2e80b4490955f450d8ef7419a1f7052b21681c8ed2c27c15796674484ff/autobahn-17.9.3.tar.gz#md5=26c24d0049c43f902ab0b8d16a3e3ce2
Processing autobahn-17.9.3.tar.gz
Writing /tmp/easy_install-isXTBQ/autobahn-17.9.3/setup.cfg
Running autobahn-17.9.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-isXTBQ/autobahn-17.9.3/egg-dist-tmp-hjBMer
package init file 'twisted/plugins/__init__.py' not found (or not a regular file)
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    install_requires=['twisted', 'ecdsa', 'pyopenssl', 'autobahn',]
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 358, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 578, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 630, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 682, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 580, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 825, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/pkg_resources.py", line 837, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 598, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 628, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 823, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 1103, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/command/easy_install.py", line 1089, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 30, in run_setup
    lambda: execfile(
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 78, in run
    return func()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.28-py2.7.egg/setuptools/sandbox.py", line 32, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 253, in <module>
    
  File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 23, in <module>
    from twisted.python import log
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 26, in <module>
    from twisted.logger import (
  File "/usr/lib/python2.7/dist-packages/twisted/logger/__init__.py", line 97, in <module>
    from ._logger import Logger, _loggerFor
  File "/usr/lib/python2.7/dist-packages/twisted/logger/_logger.py", line 262, in <module>
    _log = Logger()
  File "/usr/lib/python2.7/dist-packages/twisted/logger/_logger.py", line 58, in __init__
    from ._global import globalLogPublisher
  File "/usr/lib/python2.7/dist-packages/twisted/logger/_global.py", line 216, in <module>
    globalLogBeginner = LogBeginner(globalLogPublisher, sys.stderr, sys, warnings)
  File "/usr/lib/python2.7/dist-packages/twisted/logger/_global.py", line 86, in __init__
    errorStream, lambda event: formatEvent(event) + u"\n"
  File "/usr/lib/python2.7/dist-packages/twisted/logger/_file.py", line 34, in __init__
    if ioType(outFile) is not unicode:
  File "/usr/lib/python2.7/dist-packages/twisted/python/compat.py", line 381, in ioType
    if isinstance(fileIshObject, file):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

What can I do to fix this?

**Comment by TheSerapher** [comment]
Search the other repositories which are responsible for Stratum. This is an issue tracker for MPOS only, for other components please see their respective issue trackers.
