### ISSUE TITLE
~/stratum-mining/externals/stratum# sudo python setup.py install >> error

### ISSUE THREAD

**Issue by prosenjitgit** [MPOS/php-mpos#2637]
When I try to install python setup.py install inside folder of ~/stratum-mining/externals/stratum Then I'm getting error....

Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/root/stratum-mining/externals/stratum/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/root/stratum-mining/externals/stratum/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/root/stratum-mining/externals/stratum/distribute_setup.py", line 194, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

**Comment by TheSerapher** [comment]
You could have searched this repository for this specific question which has been dealt with in the past: This is not an issue with MPOS itself so please go ask the proper channels for this product.
