### ISSUE TITLE
Not able to configure Ticker price update ^^

### ISSUE THREAD

**Issue by TheCryptoServices** [MPOS/php-mpos#2733]
Hi again. 
I'm trying to make price update from cryptopia api works with mpos.. but no way!

I have in config:
$config['price']['enabled'] = true;
$config['price']['url'] = 'https://www.cryptopia.co.nz/';
$config['price']['target'] = 'api/GetMarket/100';
$config['price']['currency'] = 'BTC';

executing the query on browser
https://www.cryptopia.co.nz/api/GetMarket/100

 i get:

{"Success":true,"Message":null,"Data":{"TradePairId":100,"Label":"DOT/BTC","AskPrice":0.00000196,"BidPrice":0.00000193,"Low":0.00000189,"High":0.00000208,"Volume":2430233.51621936,"LastPrice":0.00000198,"BuyVolume":35588695.18387695,"SellVolume":60413458.24151218,"Change":-1.98,"Open":0.00000202,"Close":0.00000198,"BaseVolume":4.73218882,"BuyBaseVolume":25.59819524,"SellBaseVolume":12225600.22362245},"Error":null}

But in the ticker logs i get only this:

2018-05-18 14:27:03 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-18 14:27:03 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |
2018-05-18 14:28:02 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-18 14:28:02 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |
2018-05-18 14:29:02 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-18 14:29:02 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |

What I am doing wrong?

**Comment by cornac** [comment]
$config['price']['enabled'] = true;
$config['price']['url'] = 'https://www.cryptopia.co.nz';
$config['price']['target'] = '/api/GetMarket/DEM_BTC';
$config['price']['currency'] = 'BTC';
Chose market for your coin

**Comment by TheCryptoServices** [comment]
That didnt worked for me :(

**Comment by cornac** [comment]
Is cryptopia ticker implement in include/classes/tools.class.php?

**Comment by TheCryptoServices** [comment]
Yes, cryptopia included in tools.class.php

 private function getApiType($url) {
    if (preg_match('/coinchoose.com/', $url)) {
      return 'coinchoose';
    } else if (preg_match('/btc-e.nz/', $url)) {
      return 'btce';
    } else if (preg_match('/cryptopia.co.nz/', $url)) {
     return 'cryptopia';
    } else if (preg_match('/cryptorush.in/', $url)) {

Btw, I tried with other exchanges, like bittrex and yobit... but same results .
Hashrate in dashboard is correct, but I'm using different keys from memcache becouse I'm running several instances of mpos with several coins... do I need to use custom memcache keys somewhere else?

Ty!

**Comment by cornac** [comment]
In global.inc.php $config['memcache']['keyprefix'] = 'mpos_dot';
But strange that in log no output. 
Cronjobs work fine?

**Comment by TheCryptoServices** [comment]
Yes, already have a different key for every coin there.
And yes.. cronjob executing every minute without problems... but in the tickerupdate log there is nothing 

2018-05-19 4:40:03 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-19 4:40:03 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |
2018-05-19 4:41:02 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-19 4:41:02 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |
2018-05-19 4:42:03 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-19 4:42:03 - INFO --> | Method                    |           Value |  Runtime | Status | Message                                                                          |
2018-05-19 4:43:03 - INFO --> Running periodic tasks to update database values for GUI access
2018-05-19 4:43:03 - INFO --> | Method                    |           Value |  Runtime | Status | Message  

Super strange :(

**Comment by cornac** [comment]
Try to run manual mpos/cronjobs/tickerupdate.php 
And check permissions to it. 
I think it’s not running, because no output to logs

**Comment by TheCryptoServices** [comment]
/pools/egulden/cronjobs$ ls -l tickerupdate.php
-rwxrwxrwx 1 mpos mpos 2602 abr 23 20:37 tickerupdate.php

ah! I found this error now in logs:
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /home/mpos/pools/chauchera/include/classes/tools.class.php:43
Stack trace:
#0 /home/mpos/pools/egulden/include/classes/tools.class.php(113): Tools->getApi('https://www.cry...', '/api/GetMarket/...')
#1 /home/mpos/pools/egulden/cronjobs/tickerupdate.php(43): Tools->getPrice()
#2 {main}
  thrown in /home/mpos/pools/egulden/include/classes/tools.class.php on line 43

**Comment by cornac** [comment]
sudo apt-get install curl

**Comment by TheCryptoServices** [comment]
Yes, trying that, I'm using php 5.6 so I installed 
sudo apt-get install php5.6-curl

but still getting same error..
looking on that now...

**Comment by cornac** [comment]
For several directories for pid file of crons add to cronjobs start lines “parameter -d coinname”
Like this *  *    * * *   root /var/www/cryptopool.gq/mpos-maza/cronjobs/run-statistics.sh -f -d maza

**Comment by TheCryptoServices** [comment]
Well.. i'm still getting the same error
Uncaught Error: Call to undefined function curl_init() in /home/mpos/pools/egulden/include/classes/tools.class.php:43

I installed curl and activated the extension in php.ini
extension=curl.so

restarted apache
but still the same :/

**Comment by cornac** [comment]
I’m learning too)
