### ISSUE TITLE
Please answer

### ISSUE THREAD

**Issue by dongpu1813** [MPOS/php-mpos#2769]
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    use_setuptools()
  File "/home/pool/compil/stratum-mining/externals/stratum/distribute_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pool/compil/stratum-mining/externals/stratum/distribute_setup.py", line 124, in _do_download
    to_dir, download_delay)
  File "/home/pool/compil/stratum-mining/externals/stratum/distribute_setup.py", line 194, in download_setuptools
    src = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

**Comment by dongpu1813** [comment]
趋势项目
趋势项目由社区下载

dagster 0.2.8.post0
Dagster是数据管道的一种固执的编程模型。
csr_aws_utils 0.0.58
AWS上的csr1000v实用程序
briefed -people-utils 0.6.7
支持收集公共可用数据并将其发送给Briefed的工具。
robobrowser 0.5.3
友好的邻居网络刮刀
azure-iot-provisioning-device-client 1.4.5
物联网配置设备客户端库
新版本
热门新闻：最新项目发布

bgionlinecli 3.0.1.2
适用于Python的BGI Online Platform API绑定
ssr-utils 3.1.5
Shadowsocks（R）utils。
tf-nightly-2.0-preview 1.13.0.dev20181216
TensorFlow是一个适合每个人的开源机器学习框架。
tf-nightly 1.13.0.dev20181216
TensorFlow是一个适合每个人的开源机器学习框架。
devpackage 0.1
